### PR TITLE
Address #108.

### PR DESCRIPTION
**Pull request by mjordan**
Github issue: https://github.com/Islandora-Labs/islandora_vagrant/issues/108
# What does this Pull Request do?

Adds some details to the requirements necessary to run the Vagrant.
# What's new?

Added a bullet to the Requirements section under VirtualBox, and a brief note that that virtualization must be enabled in the host machine's BIOS settings.
# How should this be tested?

No testing required other than to judge whether the new information is useful and clear.
# Additional Notes

None.
# Interested parties

@lutaylor and @DonRichards

### CODE REVIEW

**Comment by DonRichards** [comment]
So why do you say "... that virtualization must be enabled in the host machine's BIOS settings."?

I believe it would be highly suggested but I'm not sure it would be a requirement. The reason I say this is "... VirtualBox does not require hardware virtualization features to be present."

https://www.virtualbox.org/manual/ch10.html#hwvirt

The except is VirtualBox's 64-bit guest support. Otherwise everything else looks good.

**Comment by mjordan** [comment]
The documentation about when hardware virtualization is required is less than clear, at least to me. Providing guidance on exactly when it is required will be challenging. I'm happy to soften the note to "may be required" but given that the Islandora Vagrant base box is running Trusty 64, and that enabling hardware virtualization here at iCamp helped us get it working on a few machinese, it's definitely required in some instances.

**Comment by lutaylor** [comment]
On newer systems it is generally enabled by default if I am not mistaken. However I agree with @mjordan that this should be a listed requirement given that we are using 64bit.

**Comment by DonRichards** [comment]
Sounds, good. Just wanted to discuss this a bit further.

**Pull request merged**
