### PR TITLE
Basebox issue-28

### PR DESCRIPTION
**Pull request by lutaylor**
**JIRA Ticket**: https://github.com/Islandora-Labs/islandora_vagrant_base_box/issues/28 (no JIRA just issue in queue)

# What does this Pull Request do?

Updates variables to match PR in basebox https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/29

# What's new?
New Solr, FITS, and Solr home. 

Updated variables that are reflected in https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/29

# How should this be tested?

Make sure you test this with https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/29.

# Additional Notes:

# Interested parties
@DonRichards
@Natkeeran

### CODE REVIEW

**Comment by jordandukart** [comment]
Thanks for pointing that out @ruebot and @lutaylor for all of his gracious hard work :)!

**Comment by lutaylor** [comment]
Updated to FITS 1.1.1 as per @ruebot  comment.

**Comment by DonRichards** [comment]
Testing the base box currently. As soon as that passes and the PR is merged I'll test this one.

**Comment by lutaylor** [comment]
Having any luck?

**Comment by DonRichards** [comment]
OK, looks good.

**Review by DonRichards — APPROVED** [review]
Works and looks good. Thanks for the PR

**Pull request merged**
