### PR TITLE
Add cantaloupe Login and location

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: N/A

# What does this Pull Request do?
Adds info for Cantaloupe login

# What's new?
Documentation

# How should this be tested?
Check URL and login works

# Additional Notes:
N/A

# Interested parties
@Islandora-Labs/committers

### CODE REVIEW

**Comment by DonRichards** [comment]
@br2490 Would you mind looking at this?

**Comment by br2490** [comment]
@DonRichards If you can add the password (admin) it LGTM.

**Review by br2490 — APPROVED** [review]

**Comment by br2490** [comment]
@DonRichards LGTM, I can't merge, so please don't wait on me!

**Review by dannylamb — APPROVED** [review]
:shipit:

**Pull request merged**
