### PR TITLE
add directory path shortcuts

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: N/A

* Corrects the issue https://github.com/Islandora-Labs/islandora_vagrant/issues/137

# What does this Pull Request do?

Adds the path shortcuts to the .bashrc file

# What's new?
### Added to .bashrc
```.bashrc
export DOWNLOAD_DIR="$SHARED_DIR/downloads"
export DJATOKA_HOME="/usr/local/djatoka"
export FEDORA_HOME="/usr/local/fedora"
export FITS_HOME="/usr/local/fits"
export SOLR_HOME="/usr/local/solr"
export DRUPAL_HOME="/var/www/drupal"
```

# How should this be tested?

Run this before switching to this PR and again after you switch to this PR and `vagrant destroy -f && vagrant up`

```terminal
$ vagrant ssh
$ cd $DRUPAL_HOME
$ pwd
$ /var/www/drupal

```

# Additional Notes:
N/A

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-Labs/committers

### CODE REVIEW

**Comment by rosiel** [comment]
this actually would be kinda useful! Alternately, I was going to list all the important directories in the login branding (e.g. 'drupal root is at /var/www/drupal' etc). This might be better, and less intrusive.

 @DiegoPino what do you think?

**Comment by DiegoPino** [comment]
Totally useful, thanks, @DonRichards  ! But I'm picky (and grumpy, old, hungry) and I have a request, can we reuse the already created paths from here https://github.com/Islandora-Labs/islandora_vagrant/blob/master/configs/variablesand/or set there the missing ones there, to allow  .bashrc to be dynamically modified based on the actual installation paths? I mean, someone can change that variable at home and then the ENV won't match? Friday and tired.. so excuse my pickyness.

**Comment by DonRichards** [comment]
@DiegoPino you like this approach better? 

```bash
echo -en "if [ -f /vagrant/configs/variables ]; then
     . /vagrant/configs/variables
fi" >> /home/vagrant/.bashrc
```

**Review by lutaylor — APPROVED** [review]
Tested works as described.

**Pull request merged**
